version: '3.7'

services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres

  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=8000
    depends_on:
      - server
    stdin_open: true
    tty: true

  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat_db
    ports:
      - "5432:5432"

volumes:
  postgres: